<a href="https://colab.research.google.com/github/RaaviSiddardha/data-science-project/blob/main/iit_nit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install -U scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install matplotlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install seaborn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [ ]:
sample_data = pd.read_csv('/content/data.csv')


In [ ]:
sample_data.head()

id  year institute_type  round_no quota            pool institute_short  \
0   1  2016            IIT         6    AI  Gender-Neutral      IIT-Bombay   
1   2  2016            IIT         6    AI  Gender-Neutral      IIT-Bombay   
2   3  2016            IIT         6    AI  Gender-Neutral      IIT-Bombay   
3   4  2016            IIT         6    AI  Gender-Neutral      IIT-Bombay   
4   5  2016            IIT         6    AI  Gender-Neutral      IIT-Bombay   

            program_name program_duration degree_short category  opening_rank  \
0  Aerospace Engineering          4 Years       B.Tech      GEN           838   
1  Aerospace Engineering          4 Years       B.Tech  OBC-NCL           408   
2  Aerospace Engineering          4 Years       B.Tech       SC           297   
3  Aerospace Engineering          4 Years       B.Tech       ST            79   
4  Aerospace Engineering          4 Years       B.Tech  GEN-PWD            94   

   closing_rank  is_preparatory  
0          1841               0  
1          1098               0  
2           468               0  
3           145               0  
4            94               0

In [ ]:
sample_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64958 entries, 0 to 64957
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   id                64958 non-null  int64 
 1   year              64958 non-null  int64 
 2   institute_type    64958 non-null  object
 3   round_no          64958 non-null  int64 
 4   quota             64958 non-null  object
 5   pool              64958 non-null  object
 6   institute_short   64958 non-null  object
 7   program_name      64958 non-null  object
 8   program_duration  64958 non-null  object
 9   degree_short      64958 non-null  object
 10  category          64958 non-null  object
 11  opening_rank      64958 non-null  int64 
 12  closing_rank      64958 non-null  int64 
 13  is_preparatory    64958 non-null  int64 
dtypes: int64(6), object(8)
memory usage: 6.9+ MB


In [ ]:
sample_data.fillna(0).inplace=True

In [ ]:
sample_data.nunique()

id                  25458
year                    6
institute_type          2
round_no                4
quota                   7
pool                    2
institute_short        54
program_name          130
program_duration        2
degree_short           13
category               10
opening_rank        10984
closing_rank        11940
is_preparatory          2
dtype: int64

# Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
sample_data['institute_type'] = label_encoder.fit_transform(sample_data['institute_type'])
sample_data['institute_short'] = label_encoder.fit_transform(sample_data['institute_short'])
sample_data['program_duration'] = label_encoder.fit_transform(sample_data['program_duration'])
sample_data['degree_short'] = label_encoder.fit_transform(sample_data['degree_short'])
sample_data['quota'] = label_encoder.fit_transform(sample_data['quota'])
sample_data['pool'] = label_encoder.fit_transform(sample_data['pool'])
sample_data['category'] = label_encoder.fit_transform(sample_data['category'])
sample_data['program_name'] = label_encoder.fit_transform(sample_data['program_name'])



In [ ]:

sample_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64958 entries, 0 to 64957
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                64958 non-null  int64
 1   year              64958 non-null  int64
 2   institute_type    64958 non-null  int64
 3   round_no          64958 non-null  int64
 4   quota             64958 non-null  int64
 5   pool              64958 non-null  int64
 6   institute_short   64958 non-null  int64
 7   program_name      64958 non-null  int64
 8   program_duration  64958 non-null  int64
 9   degree_short      64958 non-null  int64
 10  category          64958 non-null  int64
 11  opening_rank      64958 non-null  int64
 12  closing_rank      64958 non-null  int64
 13  is_preparatory    64958 non-null  int64
dtypes: int64(14)
memory usage: 6.9 MB


In [ ]:
sample_data.head()

id  year  institute_type  round_no  quota  pool  institute_short  \
0   1  2016               0         6      0     1                4   
1   2  2016               0         6      0     1                4   
2   3  2016               0         6      0     1                4   
3   4  2016               0         6      0     1                4   
4   5  2016               0         6      0     1                4   

   program_name  program_duration  degree_short  category  opening_rank  \
0             0                 0             4         0           838   
1             0                 0             4         4           408   
2             0                 0             4         6           297   
3             0                 0             4         8            79   
4             0                 0             4         3            94   

   closing_rank  is_preparatory  
0          1841               0  
1          1098               0  
2           468               0  
3           145               0  
4            94               0

# one hot encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder
hlo = OneHotEncoder()
feature_label = hlo.fit_transform(sample_data[['quota','pool','program_name','category']]).toarray()
print(feature_label)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
sample_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64958 entries, 0 to 64957
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                64958 non-null  int64
 1   year              64958 non-null  int64
 2   institute_type    64958 non-null  int64
 3   round_no          64958 non-null  int64
 4   quota             64958 non-null  int64
 5   pool              64958 non-null  int64
 6   institute_short   64958 non-null  int64
 7   program_name      64958 non-null  int64
 8   program_duration  64958 non-null  int64
 9   degree_short      64958 non-null  int64
 10  category          64958 non-null  int64
 11  opening_rank      64958 non-null  int64
 12  closing_rank      64958 non-null  int64
 13  is_preparatory    64958 non-null  int64
dtypes: int64(14)
memory usage: 6.9 MB


In [ ]:
sample_data.head(10)

id  year  institute_type  round_no  quota  pool  institute_short  \
0   1  2016               0         6      0     1                4   
1   2  2016               0         6      0     1                4   
2   3  2016               0         6      0     1                4   
3   4  2016               0         6      0     1                4   
4   5  2016               0         6      0     1                4   
5   6  2016               0         6      0     1                4   
6   7  2016               0         6      0     1                4   
7   8  2016               0         6      0     1                4   
8   9  2016               0         6      0     1                4   
9  10  2016               0         6      0     1                4   

   program_name  program_duration  degree_short  category  opening_rank  \
0             0                 0             4         0           838   
1             0                 0             4         4           408   
2             0                 0             4         6           297   
3             0                 0             4         8            79   
4             0                 0             4         3            94   
5             0                 0             4         5            45   
6            28                 0             4         0           422   
7            28                 0             4         4           447   
8            28                 0             4         6           257   
9            28                 0             4         8           161   

   closing_rank  is_preparatory  
0          1841               0  
1          1098               0  
2           468               0  
3           145               0  
4            94               0  
5            45               0  
6          1479               0  
7           974               0  
8           572               0  
9           335               0

In [ ]:
sample_data.nunique()

id                  25458
year                    6
institute_type          2
round_no                4
quota                   7
pool                    2
institute_short        54
program_name          130
program_duration        2
degree_short           13
category               10
opening_rank        10984
closing_rank        11940
is_preparatory          2
dtype: int64

In [ ]:
sample_data.head()

id  year  institute_type  round_no  quota  pool  institute_short  \
0   1  2016               0         6      0     1                4   
1   2  2016               0         6      0     1                4   
2   3  2016               0         6      0     1                4   
3   4  2016               0         6      0     1                4   
4   5  2016               0         6      0     1                4   

   program_name  program_duration  degree_short  category  opening_rank  \
0             0                 0             4         0           838   
1             0                 0             4         4           408   
2             0                 0             4         6           297   
3             0                 0             4         8            79   
4             0                 0             4         3            94   

   closing_rank  is_preparatory  
0          1841               0  
1          1098               0  
2           468               0  
3           145               0  
4            94               0

In [ ]:
sample_data.tail()

id  year  institute_type  round_no  quota  pool  institute_short  \
64953  31136  2021               1         1      4     0               49   
64954  31137  2021               1         1      4     1               49   
64955  31138  2021               1         1      4     0               49   
64956  31139  2021               1         1      5     1               49   
64957  31140  2021               1         1      5     0               49   

       program_name  program_duration  degree_short  category  opening_rank  \
64953            57                 0             4         6         14185   
64954            57                 0             4         8          2736   
64955            57                 0             4         8         10870   
64956            57                 0             4         0        166453   
64957            57                 0             4         0        215054   

       closing_rank  is_preparatory  
64953         24048               0  
64954          4171               0  
64955         10870               0  
64956        265454               0  
64957        215054               0

In [ ]:
sample_data.isna().sum()

id                  0
year                0
institute_type      0
round_no            0
quota               0
pool                0
institute_short     0
program_name        0
program_duration    0
degree_short        0
category            0
opening_rank        0
closing_rank        0
is_preparatory      0
dtype: int64

In [ ]:
sample_data['is_preparatory'].value_counts()

0    61864
1     3094
Name: is_preparatory, dtype: int64

0 - iit
1 - nit

In [ ]:
sample_data.describe()

id          year  institute_type      round_no         quota  \
count  64958.000000  64958.000000    64958.000000  64958.000000  64958.000000   
mean   18171.173389   2020.421580        0.493442      2.609348      2.265141   
std     9619.123659      1.149762        0.499961      2.422558      2.527374   
min        1.000000   2016.000000        0.000000      1.000000      0.000000   
25%    10378.000000   2020.000000        0.000000      1.000000      0.000000   
50%    13084.500000   2021.000000        0.000000      1.000000      0.000000   
75%    28434.000000   2021.000000        1.000000      6.000000      6.000000   
max    31140.000000   2021.000000        1.000000      7.000000      6.000000   

               pool  institute_short  program_name  program_duration  \
count  64958.000000     64958.000000  64958.000000      64958.000000   
mean       0.597078        23.271144     58.270575          0.162012   
std        0.490489        14.625058     32.729567          0.368465   
min        0.000000         0.000000      0.000000          0.000000   
25%        0.000000        13.000000     32.000000          0.000000   
50%        1.000000        22.000000     47.000000          0.000000   
75%        1.000000        35.000000     93.000000          0.000000   
max        1.000000        53.000000    129.000000          1.000000   

       degree_short      category  opening_rank  closing_rank  is_preparatory  
count  64958.000000  64958.000000  6.495800e+04  6.495800e+04    64958.000000  
mean       4.360294      3.778503  8.259642e+03  1.070497e+04        0.047631  
std        1.447724      2.859502  2.679448e+04  3.788101e+04        0.212985  
min        0.000000      0.000000  0.000000e+00  0.000000e+00        0.000000  
25%        4.000000      1.000000  6.710000e+02  8.320000e+02        0.000000  
50%        4.000000      4.000000  2.309000e+03  2.764500e+03        0.000000  
75%        4.000000      6.000000  6.932000e+03  8.190000e+03        0.000000  
max       12.000000      9.000000  1.082601e+06  1.144790e+06        1.000000

In [ ]:
sample_data.shape

(64958, 14)

In [ ]:
sample_data.groupby('is_preparatory').mean()

id         year  institute_type  round_no     quota  \
is_preparatory                                                                  
0               18549.512317  2020.403223         0.51812  2.636137  2.378427   
1               10606.351325  2020.788623         0.00000  2.073691  0.000000   

                    pool  institute_short  program_name  program_duration  \
is_preparatory                                                              
0               0.603388        23.877021     58.113717          0.156359   
1               0.470911        11.156755     61.406917          0.275048   

                degree_short  category  opening_rank  closing_rank  
is_preparatory                                                      
0                   4.342170  3.646903   8649.975155  11215.537033  
1                   4.722689  6.409825    454.993859    496.303167

In [ ]:
sample_data.tail()

id  year  institute_type  round_no  quota  pool  institute_short  \
64953  31136  2021               1         1      4     0               49   
64954  31137  2021               1         1      4     1               49   
64955  31138  2021               1         1      4     0               49   
64956  31139  2021               1         1      5     1               49   
64957  31140  2021               1         1      5     0               49   

       program_name  program_duration  degree_short  category  opening_rank  \
64953            57                 0             4         6         14185   
64954            57                 0             4         8          2736   
64955            57                 0             4         8         10870   
64956            57                 0             4         0        166453   
64957            57                 0             4         0        215054   

       closing_rank  is_preparatory  
64953         24048               0  
64954          4171               0  
64955         10870               0  
64956        265454               0  
64957        215054               0

In [ ]:
 x = sample_data.drop(columns = 'is_preparatory',axis =1)
 y = sample_data['is_preparatory']

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,stratify = y,random_state = 1)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(64958, 13) (51966, 13) (12992, 13)


In [ ]:
print(y.shape,y_train.shape,y_test.shape)

(64958,) (51966,) (12992,)


In [ ]:
model =LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)

In [ ]:
print(training_data_accuracy)

0.9504868567909787


In [ ]:
x_test_prediction = model.predict(x_test)
tesing_data_accuracy = accuracy_score(x_test_prediction,y_test)

In [ ]:
print(tesing_data_accuracy)

0.9505849753694581
